version: '3.2'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python3 django_blog/manage.py runserver 0.0.0.0:8990
    volumes:
      - .:/code
    ports:
      - "8990:8990"
    depends_on:
      - db

volumes:
  postgres_data:
